/*
 * Automatically generated C config: don't edit
 * Linux kernel version: 2.6.11.12
 * Sun May 16 16:58:21 2021
 */
#ifndef __KERNEL__
#define __KERNEL__
#endif
#define AUTOCONF_INCLUDED
#define CONFIG_X86 1
#define CONFIG_MMU 1
#define CONFIG_UID16 1
#define CONFIG_GENERIC_ISA_DMA 1
#define CONFIG_GENERIC_IOMAP 1

/*
 * Code maturity level options
 */
#undef CONFIG_EXPERIMENTAL
#define CONFIG_CLEAN_COMPILE 1
#define CONFIG_LOCK_KERNEL 1

/*
 * General setup
 */
#define CONFIG_LOCALVERSION ""
#define CONFIG_SWAP 1
#define CONFIG_SYSVIPC 1
#define CONFIG_BSD_PROCESS_ACCT 1
#define CONFIG_BSD_PROCESS_ACCT_V3 1
#define CONFIG_SYSCTL 1
#define CONFIG_AUDIT 1
#define CONFIG_AUDITSYSCALL 1
#define CONFIG_LOG_BUF_SHIFT 17
#define CONFIG_HOTPLUG 1
#define CONFIG_KOBJECT_UEVENT 1
#undef CONFIG_IKCONFIG
#undef CONFIG_EMBEDDED
#define CONFIG_KALLSYMS 1
#define CONFIG_KALLSYMS_ALL 1
#define CONFIG_KALLSYMS_EXTRA_PASS 1
#define CONFIG_FUTEX 1
#define CONFIG_EPOLL 1
#undef CONFIG_CC_OPTIMIZE_FOR_SIZE
#define CONFIG_SHMEM 1
#define CONFIG_CC_ALIGN_FUNCTIONS 0
#define CONFIG_CC_ALIGN_LABELS 0
#define CONFIG_CC_ALIGN_LOOPS 0
#define CONFIG_CC_ALIGN_JUMPS 0
#undef CONFIG_TINY_SHMEM

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#define CONFIG_MODULE_UNLOAD 1
#define CONFIG_OBSOLETE_MODPARM 1
#define CONFIG_MODULE_SRCVERSION_ALL 1
#undef CONFIG_KMOD
#define CONFIG_STOP_MACHINE 1

/*
 * Processor type and features
 */
#define CONFIG_X86_PC 1
#undef CONFIG_X86_ELAN
#undef CONFIG_X86_VOYAGER
#undef CONFIG_X86_NUMAQ
#undef CONFIG_X86_SUMMIT
#undef CONFIG_X86_BIGSMP
#undef CONFIG_X86_VISWS
#undef CONFIG_X86_GENERICARCH
#undef CONFIG_X86_ES7000
#undef CONFIG_M386
#undef CONFIG_M486
#undef CONFIG_M586
#undef CONFIG_M586TSC
#undef CONFIG_M586MMX
#define CONFIG_M686 1
#undef CONFIG_MPENTIUMII
#undef CONFIG_MPENTIUMIII
#undef CONFIG_MPENTIUMM
#undef CONFIG_MPENTIUM4
#undef CONFIG_MK6
#undef CONFIG_MK7
#undef CONFIG_MK8
#undef CONFIG_MCRUSOE
#undef CONFIG_MEFFICEON
#undef CONFIG_MWINCHIPC6
#undef CONFIG_MWINCHIP2
#undef CONFIG_MWINCHIP3D
#undef CONFIG_MCYRIXIII
#undef CONFIG_MVIAC3_2
#define CONFIG_X86_GENERIC 1
#define CONFIG_X86_CMPXCHG 1
#define CONFIG_X86_XADD 1
#define CONFIG_X86_L1_CACHE_SHIFT 7
#define CONFIG_RWSEM_XCHGADD_ALGORITHM 1
#define CONFIG_GENERIC_CALIBRATE_DELAY 1
#define CONFIG_X86_PPRO_FENCE 1
#define CONFIG_X86_WP_WORKS_OK 1
#define CONFIG_X86_INVLPG 1
#define CONFIG_X86_BSWAP 1
#define CONFIG_X86_POPAD_OK 1
#define CONFIG_X86_GOOD_APIC 1
#define CONFIG_X86_INTEL_USERCOPY 1
#define CONFIG_X86_USE_PPRO_CHECKSUM 1
#define CONFIG_HPET_TIMER 1
#define CONFIG_SMP 1
#define CONFIG_NR_CPUS 8
#define CONFIG_SCHED_SMT 1
#undef CONFIG_PREEMPT
#define CONFIG_X86_LOCAL_APIC 1
#define CONFIG_X86_IO_APIC 1
#define CONFIG_X86_TSC 1
#define CONFIG_X86_MCE 1
#undef CONFIG_X86_MCE_NONFATAL
#undef CONFIG_X86_MCE_P4THERMAL
#undef CONFIG_TOSHIBA
#define CONFIG_I8K_MODULE 1
#define CONFIG_MICROCODE 1
#define CONFIG_X86_MSR_MODULE 1
#define CONFIG_X86_CPUID_MODULE 1

/*
 * Firmware Drivers
 */
#define CONFIG_EFI_VARS 1
#undef CONFIG_NOHIGHMEM
#undef CONFIG_HIGHMEM4G
#define CONFIG_HIGHMEM64G 1
#define CONFIG_HIGHMEM 1
#undef CONFIG_X86_PAE
#define CONFIG_HIGHPTE 1
#undef CONFIG_MATH_EMULATION
#define CONFIG_MTRR 1
#define CONFIG_EFI 1
#define CONFIG_IRQBALANCE 1
#define CONFIG_HAVE_DEC_LOCK 1
#define CONFIG_BOOT_IOREMAP 1

/*
 * Power management options (ACPI, APM)
 */
#define CONFIG_PM 1
#define CONFIG_PM_DEBUG 1

/*
 * ACPI (Advanced Configuration and Power Interface) Support
 */
#define CONFIG_ACPI 1
#define CONFIG_ACPI_BOOT 1
#define CONFIG_ACPI_INTERPRETER 1
#define CONFIG_ACPI_AC 1
#define CONFIG_ACPI_BATTERY 1
#define CONFIG_ACPI_BUTTON 1
#define CONFIG_ACPI_FAN 1
#define CONFIG_ACPI_PROCESSOR 1
#define CONFIG_ACPI_THERMAL 1
#define CONFIG_ACPI_ASUS_MODULE 1
#define CONFIG_ACPI_IBM_MODULE 1
#define CONFIG_ACPI_TOSHIBA_MODULE 1
#define CONFIG_ACPI_BLACKLIST_YEAR 0
#undef CONFIG_ACPI_DEBUG
#define CONFIG_ACPI_BUS 1
#define CONFIG_ACPI_EC 1
#define CONFIG_ACPI_POWER 1
#define CONFIG_ACPI_PCI 1
#define CONFIG_ACPI_SYSTEM 1

/*
 * APM (Advanced Power Management) BIOS Support
 */
#define CONFIG_APM_MODULE 1
#undef CONFIG_APM_IGNORE_USER_SUSPEND
#undef CONFIG_APM_DO_ENABLE
#undef CONFIG_APM_CPU_IDLE
#undef CONFIG_APM_DISPLAY_BLANK
#undef CONFIG_APM_RTC_IS_GMT
#undef CONFIG_APM_ALLOW_INTS
#undef CONFIG_APM_REAL_MODE_POWER_OFF

/*
 * CPU Frequency scaling
 */
#define CONFIG_CPU_FREQ 1
#undef CONFIG_CPU_FREQ_DEBUG
#define CONFIG_CPU_FREQ_STAT 1
#undef CONFIG_CPU_FREQ_STAT_DETAILS
#define CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE 1
#undef CONFIG_CPU_FREQ_DEFAULT_GOV_USERSPACE
#define CONFIG_CPU_FREQ_GOV_PERFORMANCE 1
#define CONFIG_CPU_FREQ_GOV_POWERSAVE 1
#define CONFIG_CPU_FREQ_GOV_USERSPACE 1
#define CONFIG_CPU_FREQ_GOV_ONDEMAND 1
#define CONFIG_CPU_FREQ_TABLE 1

/*
 * CPUFreq processor drivers
 */
#define CONFIG_X86_ACPI_CPUFREQ 1
#define CONFIG_X86_POWERNOW_K6_MODULE 1
#define CONFIG_X86_POWERNOW_K7_MODULE 1
#define CONFIG_X86_POWERNOW_K7_ACPI 1
#define CONFIG_X86_GX_SUSPMOD_MODULE 1
#define CONFIG_X86_SPEEDSTEP_CENTRINO 1
#define CONFIG_X86_SPEEDSTEP_CENTRINO_ACPI 1
#define CONFIG_X86_SPEEDSTEP_CENTRINO_TABLE 1
#define CONFIG_X86_SPEEDSTEP_ICH 1
#define CONFIG_X86_P4_CLOCKMOD_MODULE 1
#define CONFIG_X86_LONGRUN_MODULE 1
#define CONFIG_X86_LONGHAUL_MODULE 1

/*
 * shared options
 */
#undef CONFIG_X86_ACPI_CPUFREQ_PROC_INTF
#define CONFIG_X86_SPEEDSTEP_LIB 1
#define CONFIG_X86_SPEEDSTEP_RELAXED_CAP_CHECK 1

/*
 * Bus options (PCI, PCMCIA, EISA, MCA, ISA)
 */
#define CONFIG_PCI 1
#undef CONFIG_PCI_GOBIOS
#undef CONFIG_PCI_GOMMCONFIG
#undef CONFIG_PCI_GODIRECT
#define CONFIG_PCI_GOANY 1
#define CONFIG_PCI_BIOS 1
#define CONFIG_PCI_DIRECT 1
#define CONFIG_PCI_MMCONFIG 1
#define CONFIG_PCIEPORTBUS 1
#define CONFIG_PCI_MSI 1
#undef CONFIG_PCI_LEGACY_PROC
#undef CONFIG_PCI_NAMES
#define CONFIG_ISA 1
#define CONFIG_EISA 1
#define CONFIG_EISA_VLB_PRIMING 1
#define CONFIG_EISA_PCI_EISA 1
#define CONFIG_EISA_VIRTUAL_ROOT 1
#define CONFIG_EISA_NAMES 1
#undef CONFIG_MCA
#define CONFIG_SCx200_MODULE 1

/*
 * PCCARD (PCMCIA/CardBus) support
 */
#define CONFIG_PCCARD_MODULE 1
#undef CONFIG_PCMCIA_DEBUG
#define CONFIG_PCMCIA_MODULE 1
#define CONFIG_CARDBUS 1

/*
 * PC-card bridges
 */
#define CONFIG_YENTA_MODULE 1
#define CONFIG_PD6729_MODULE 1
#define CONFIG_I82092_MODULE 1
#define CONFIG_I82365_MODULE 1
#define CONFIG_TCIC_MODULE 1
#define CONFIG_PCMCIA_PROBE 1
#define CONFIG_PCCARD_NONSTATIC_MODULE 1

/*
 * PCI Hotplug Support
 */

/*
 * Executable file formats
 */
#define CONFIG_BINFMT_ELF 1
#undef CONFIG_BINFMT_AOUT
#define CONFIG_BINFMT_MISC_MODULE 1

/*
 * Device Drivers
 */

/*
 * Generic Driver Options
 */
#define CONFIG_STANDALONE 1
#define CONFIG_PREVENT_FIRMWARE_BUILD 1
#define CONFIG_FW_LOADER 1
#undef CONFIG_DEBUG_DRIVER

/*
 * Memory Technology Devices (MTD)
 */
#define CONFIG_MTD_MODULE 1
#undef CONFIG_MTD_DEBUG
#undef CONFIG_MTD_PARTITIONS
#undef CONFIG_MTD_CONCAT

/*
 * User Modules And Translation Layers
 */
#undef CONFIG_MTD_CHAR
#define CONFIG_MTD_BLOCK_MODULE 1
#define CONFIG_MTD_BLOCK_RO_MODULE 1
#define CONFIG_FTL_MODULE 1
#define CONFIG_NFTL_MODULE 1
#define CONFIG_NFTL_RW 1
#define CONFIG_INFTL_MODULE 1

/*
 * RAM/ROM/Flash chip drivers
 */
#define CONFIG_MTD_CFI_MODULE 1
#define CONFIG_MTD_JEDECPROBE_MODULE 1
#define CONFIG_MTD_GEN_PROBE_MODULE 1
#undef CONFIG_MTD_CFI_ADV_OPTIONS
#define CONFIG_MTD_MAP_BANK_WIDTH_1 1
#define CONFIG_MTD_MAP_BANK_WIDTH_2 1
#define CONFIG_MTD_MAP_BANK_WIDTH_4 1
#undef CONFIG_MTD_MAP_BANK_WIDTH_8
#undef CONFIG_MTD_MAP_BANK_WIDTH_16
#undef CONFIG_MTD_MAP_BANK_WIDTH_32
#define CONFIG_MTD_CFI_I1 1
#define CONFIG_MTD_CFI_I2 1
#undef CONFIG_MTD_CFI_I4
#undef CONFIG_MTD_CFI_I8
#define CONFIG_MTD_CFI_INTELEXT_MODULE 1
#define CONFIG_MTD_CFI_AMDSTD_MODULE 1
#define CONFIG_MTD_CFI_AMDSTD_RETRY 0
#define CONFIG_MTD_CFI_STAA_MODULE 1
#define CONFIG_MTD_CFI_UTIL_MODULE 1
#define CONFIG_MTD_RAM_MODULE 1
#define CONFIG_MTD_ROM_MODULE 1
#define CONFIG_MTD_ABSENT_MODULE 1

/*
 * Mapping drivers for chip access
 */
#define CONFIG_MTD_COMPLEX_MAPPINGS 1
#define CONFIG_MTD_PHYSMAP_MODULE 1
#define CONFIG_MTD_PHYSMAP_START 0x8000000
#define CONFIG_MTD_PHYSMAP_LEN 0x4000000
#define CONFIG_MTD_PHYSMAP_BANKWIDTH 2
#undef CONFIG_MTD_SC520CDP
#define CONFIG_MTD_AMD76XROM_MODULE 1
#define CONFIG_MTD_ICHXROM_MODULE 1
#define CONFIG_MTD_SCB2_FLASH_MODULE 1
#define CONFIG_MTD_L440GX_MODULE 1
#define CONFIG_MTD_PCI_MODULE 1

/*
 * Self-contained MTD device drivers
 */
#define CONFIG_MTD_PMC551_MODULE 1
#undef CONFIG_MTD_PMC551_BUGFIX
#undef CONFIG_MTD_PMC551_DEBUG
#define CONFIG_MTD_SLRAM_MODULE 1
#define CONFIG_MTD_PHRAM_MODULE 1
#define CONFIG_MTD_MTDRAM_MODULE 1
#define CONFIG_MTDRAM_TOTAL_SIZE 4096
#define CONFIG_MTDRAM_ERASE_SIZE 128
#undef CONFIG_MTD_BLKMTD

/*
 * Disk-On-Chip Device Drivers
 */
#undef CONFIG_MTD_DOC2000
#undef CONFIG_MTD_DOC2001
#undef CONFIG_MTD_DOC2001PLUS

/*
 * NAND Flash Device Drivers
 */
#define CONFIG_MTD_NAND_MODULE 1
#undef CONFIG_MTD_NAND_VERIFY_WRITE
#define CONFIG_MTD_NAND_IDS_MODULE 1

/*
 * Parallel port support
 */
#define CONFIG_PARPORT_MODULE 1
#define CONFIG_PARPORT_PC_MODULE 1
#define CONFIG_PARPORT_PC_CML1_MODULE 1
#define CONFIG_PARPORT_SERIAL_MODULE 1
#define CONFIG_PARPORT_PC_PCMCIA_MODULE 1
#undef CONFIG_PARPORT_OTHER
#define CONFIG_PARPORT_1284 1

/*
 * Plug and Play support
 */
#define CONFIG_PNP 1
#undef CONFIG_PNP_DEBUG

/*
 * Protocols
 */
#define CONFIG_ISAPNP 1

/*
 * Block devices
 */
#define CONFIG_BLK_DEV_FD_MODULE 1
#undef CONFIG_BLK_DEV_XD
#define CONFIG_PARIDE_MODULE 1
#define CONFIG_PARIDE_PARPORT_MODULE 1

/*
 * Parallel IDE high-level drivers
 */
#define CONFIG_PARIDE_PD_MODULE 1
#define CONFIG_PARIDE_PCD_MODULE 1
#define CONFIG_PARIDE_PF_MODULE 1
#define CONFIG_PARIDE_PT_MODULE 1
#define CONFIG_PARIDE_PG_MODULE 1

/*
 * Parallel IDE protocol modules
 */
#define CONFIG_PARIDE_ATEN_MODULE 1
#define CONFIG_PARIDE_BPCK_MODULE 1
#define CONFIG_PARIDE_BPCK6_MODULE 1
#define CONFIG_PARIDE_COMM_MODULE 1
#define CONFIG_PARIDE_DSTR_MODULE 1
#define CONFIG_PARIDE_FIT2_MODULE 1
#define CONFIG_PARIDE_FIT3_MODULE 1
#define CONFIG_PARIDE_EPAT_MODULE 1
#define CONFIG_PARIDE_EPIA_MODULE 1
#define CONFIG_PARIDE_FRIQ_MODULE 1
#define CONFIG_PARIDE_FRPW_MODULE 1
#define CONFIG_PARIDE_KBIC_MODULE 1
#define CONFIG_PARIDE_KTTI_MODULE 1
#define CONFIG_PARIDE_ON20_MODULE 1
#define CONFIG_PARIDE_ON26_MODULE 1
#undef CONFIG_BLK_CPQ_DA
#undef CONFIG_BLK_CPQ_CISS_DA
#define CONFIG_BLK_DEV_DAC960_MODULE 1
#undef CONFIG_BLK_DEV_COW_COMMON
#define CONFIG_BLK_DEV_LOOP 1
#define CONFIG_BLK_DEV_CRYPTOLOOP_MODULE 1
#define CONFIG_BLK_DEV_NBD_MODULE 1
#define CONFIG_BLK_DEV_SX8_MODULE 1
#undef CONFIG_BLK_DEV_UB
#define CONFIG_BLK_DEV_RAM_MODULE 1
#define CONFIG_BLK_DEV_RAM_COUNT 16
#define CONFIG_BLK_DEV_RAM_SIZE 65536
#define CONFIG_INITRAMFS_SOURCE ""
#undef CONFIG_LBD
#define CONFIG_CDROM_PKTCDVD_MODULE 1
#define CONFIG_CDROM_PKTCDVD_BUFFERS 8
#undef CONFIG_CDROM_PKTCDVD_WCACHE

/*
 * IO Schedulers
 */
#define CONFIG_IOSCHED_NOOP 1
#define CONFIG_IOSCHED_AS 1
#define CONFIG_IOSCHED_DEADLINE 1
#define CONFIG_IOSCHED_CFQ 1
#define CONFIG_ATA_OVER_ETH_MODULE 1

/*
 * ATA/ATAPI/MFM/RLL support
 */
#undef CONFIG_IDE

/*
 * SCSI device support
 */
#define CONFIG_SCSI 1
#define CONFIG_SCSI_PROC_FS 1

/*
 * SCSI support type (disk, tape, CD-ROM)
 */
#define CONFIG_BLK_DEV_SD 1
#define CONFIG_CHR_DEV_ST_MODULE 1
#define CONFIG_CHR_DEV_OSST_MODULE 1
#define CONFIG_BLK_DEV_SR 1
#undef CONFIG_BLK_DEV_SR_VENDOR
#define CONFIG_CHR_DEV_SG 1

/*
 * Some SCSI devices (e.g. CD jukebox) support multiple LUNs
 */
#undef CONFIG_SCSI_MULTI_LUN
#define CONFIG_SCSI_CONSTANTS 1
#define CONFIG_SCSI_LOGGING 1

/*
 * SCSI Transport Attributes
 */
#define CONFIG_SCSI_SPI_ATTRS_MODULE 1
#define CONFIG_SCSI_FC_ATTRS_MODULE 1
#define CONFIG_SCSI_ISCSI_ATTRS_MODULE 1

/*
 * SCSI low-level drivers
 */
#define CONFIG_BLK_DEV_3W_XXXX_RAID_MODULE 1
#define CONFIG_SCSI_3W_9XXX_MODULE 1
#undef CONFIG_SCSI_7000FASST
#define CONFIG_SCSI_ACARD_MODULE 1
#define CONFIG_SCSI_AHA152X_MODULE 1
#define CONFIG_SCSI_AHA1542_MODULE 1
#define CONFIG_SCSI_AHA1740_MODULE 1
#define CONFIG_SCSI_AACRAID_MODULE 1
#define CONFIG_SCSI_AIC7XXX_MODULE 1
#define CONFIG_AIC7XXX_CMDS_PER_DEVICE 8
#define CONFIG_AIC7XXX_RESET_DELAY_MS 5000
#undef CONFIG_AIC7XXX_PROBE_EISA_VL
#undef CONFIG_AIC7XXX_DEBUG_ENABLE
#define CONFIG_AIC7XXX_DEBUG_MASK 0
#define CONFIG_AIC7XXX_REG_PRETTY_PRINT 1
#undef CONFIG_SCSI_AIC7XXX_OLD
#define CONFIG_SCSI_AIC79XX_MODULE 1
#define CONFIG_AIC79XX_CMDS_PER_DEVICE 32
#define CONFIG_AIC79XX_RESET_DELAY_MS 5000
#undef CONFIG_AIC79XX_ENABLE_RD_STRM
#undef CONFIG_AIC79XX_DEBUG_ENABLE
#define CONFIG_AIC79XX_DEBUG_MASK 0
#define CONFIG_AIC79XX_REG_PRETTY_PRINT 1
#define CONFIG_SCSI_DPT_I2O_MODULE 1
#undef CONFIG_SCSI_IN2000
#define CONFIG_MEGARAID_NEWGEN 1
#define CONFIG_MEGARAID_MM_MODULE 1
#define CONFIG_MEGARAID_MAILBOX_MODULE 1
#undef CONFIG_SCSI_SATA
#define CONFIG_SCSI_BUSLOGIC_MODULE 1
#undef CONFIG_SCSI_OMIT_FLASHPOINT
#define CONFIG_SCSI_DMX3191D_MODULE 1
#undef CONFIG_SCSI_DTC3280
#define CONFIG_SCSI_EATA_MODULE 1
#define CONFIG_SCSI_EATA_TAGGED_QUEUE 1
#define CONFIG_SCSI_EATA_LINKED_COMMANDS 1
#define CONFIG_SCSI_EATA_MAX_TAGS 16
#undef CONFIG_SCSI_EATA_PIO
#define CONFIG_SCSI_FUTURE_DOMAIN_MODULE 1
#define CONFIG_SCSI_GDTH_MODULE 1
#define CONFIG_SCSI_GENERIC_NCR5380_MODULE 1
#undef CONFIG_SCSI_GENERIC_NCR5380_MMIO
#undef CONFIG_SCSI_GENERIC_NCR53C400
#define CONFIG_SCSI_IPS_MODULE 1
#define CONFIG_SCSI_INITIO_MODULE 1
#define CONFIG_SCSI_INIA100_MODULE 1
#define CONFIG_SCSI_PPA_MODULE 1
#define CONFIG_SCSI_IMM_MODULE 1
#undef CONFIG_SCSI_IZIP_EPP16
#undef CONFIG_SCSI_IZIP_SLOW_CTR
#define CONFIG_SCSI_NCR53C406A_MODULE 1
#define CONFIG_53C700_IO_MAPPED 1
#define CONFIG_SCSI_SYM53C8XX_2_MODULE 1
#define CONFIG_SCSI_SYM53C8XX_DMA_ADDRESSING_MODE 1
#define CONFIG_SCSI_SYM53C8XX_DEFAULT_TAGS 16
#define CONFIG_SCSI_SYM53C8XX_MAX_TAGS 64
#undef CONFIG_SCSI_SYM53C8XX_IOMAPPED
#define CONFIG_SCSI_IPR_MODULE 1
#define CONFIG_SCSI_IPR_TRACE 1
#define CONFIG_SCSI_IPR_DUMP 1
#undef CONFIG_SCSI_PAS16
#undef CONFIG_SCSI_PSI240I
#define CONFIG_SCSI_QLOGIC_FAS_MODULE 1
#undef CONFIG_SCSI_QLOGIC_ISP
#undef CONFIG_SCSI_QLOGIC_FC
#define CONFIG_SCSI_QLOGIC_1280_MODULE 1
#undef CONFIG_SCSI_QLOGIC_1280_1040
#define CONFIG_SCSI_QLA2XXX 1
#undef CONFIG_SCSI_QLA21XX
#undef CONFIG_SCSI_QLA22XX
#undef CONFIG_SCSI_QLA2300
#undef CONFIG_SCSI_QLA2322
#undef CONFIG_SCSI_QLA6312
#define CONFIG_SCSI_SIM710_MODULE 1
#define CONFIG_SCSI_SYM53C416_MODULE 1
#undef CONFIG_SCSI_DC390T
#undef CONFIG_SCSI_T128
#undef CONFIG_SCSI_U14_34F
#undef CONFIG_SCSI_ULTRASTOR
#define CONFIG_SCSI_NSP32_MODULE 1
#define CONFIG_SCSI_DEBUG_MODULE 1

/*
 * PCMCIA SCSI adapter support
 */
#define CONFIG_PCMCIA_AHA152X_MODULE 1
#define CONFIG_PCMCIA_FDOMAIN_MODULE 1
#define CONFIG_PCMCIA_NINJA_SCSI_MODULE 1
#define CONFIG_PCMCIA_QLOGIC_MODULE 1
#define CONFIG_PCMCIA_SYM53C500_MODULE 1

/*
 * Old CD-ROM drivers (not SCSI, not IDE)
 */
#undef CONFIG_CD_NO_IDESCSI

/*
 * Multi-device support (RAID and LVM)
 */
#define CONFIG_MD 1
#define CONFIG_BLK_DEV_MD 1
#define CONFIG_MD_LINEAR_MODULE 1
#define CONFIG_MD_RAID0_MODULE 1
#define CONFIG_MD_RAID1_MODULE 1
#undef CONFIG_MD_RAID5
#define CONFIG_MD_MULTIPATH_MODULE 1
#define CONFIG_MD_FAULTY_MODULE 1
#define CONFIG_BLK_DEV_DM 1

/*
 * Fusion MPT device support
 */
#define CONFIG_FUSION 1
#define CONFIG_FUSION_MAX_SGE 128
#define CONFIG_FUSION_CTL_MODULE 1
#define CONFIG_FUSION_LAN_MODULE 1

/*
 * IEEE 1394 (FireWire) support
 */
#undef CONFIG_IEEE1394

/*
 * I2O device support
 */
#undef CONFIG_I2O

/*
 * Networking support
 */
#define CONFIG_NET 1

/*
 * Networking options
 */
#define CONFIG_PACKET 1
#undef CONFIG_PACKET_MMAP
#undef CONFIG_NETLINK_DEV
#define CONFIG_UNIX 1
#define CONFIG_NET_KEY_MODULE 1
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#define CONFIG_IP_ADVANCED_ROUTER 1
#define CONFIG_IP_MULTIPLE_TABLES 1
#undef CONFIG_IP_ROUTE_FWMARK
#define CONFIG_IP_ROUTE_MULTIPATH 1
#define CONFIG_IP_ROUTE_VERBOSE 1
#undef CONFIG_IP_PNP
#define CONFIG_NET_IPIP_MODULE 1
#define CONFIG_NET_IPGRE_MODULE 1
#define CONFIG_NET_IPGRE_BROADCAST 1
#define CONFIG_IP_MROUTE 1
#define CONFIG_IP_PIMSM_V1 1
#define CONFIG_IP_PIMSM_V2 1
#define CONFIG_SYN_COOKIES 1
#define CONFIG_INET_AH_MODULE 1
#define CONFIG_INET_ESP_MODULE 1
#define CONFIG_INET_IPCOMP_MODULE 1
#define CONFIG_INET_TUNNEL_MODULE 1
#define CONFIG_IP_TCPDIAG 1
#undef CONFIG_IP_TCPDIAG_IPV6

/*
 * IP: Virtual Server Configuration
 */
#define CONFIG_IP_VS_MODULE 1
#undef CONFIG_IP_VS_DEBUG
#define CONFIG_IP_VS_TAB_BITS 12

/*
 * IPVS transport protocol load balancing support
 */
#define CONFIG_IP_VS_PROTO_TCP 1
#define CONFIG_IP_VS_PROTO_UDP 1
#define CONFIG_IP_VS_PROTO_ESP 1
#define CONFIG_IP_VS_PROTO_AH 1

/*
 * IPVS scheduler
 */
#define CONFIG_IP_VS_RR_MODULE 1
#define CONFIG_IP_VS_WRR_MODULE 1
#define CONFIG_IP_VS_LC_MODULE 1
#define CONFIG_IP_VS_WLC_MODULE 1
#define CONFIG_IP_VS_LBLC_MODULE 1
#define CONFIG_IP_VS_LBLCR_MODULE 1
#define CONFIG_IP_VS_DH_MODULE 1
#define CONFIG_IP_VS_SH_MODULE 1
#define CONFIG_IP_VS_SED_MODULE 1
#define CONFIG_IP_VS_NQ_MODULE 1

/*
 * IPVS application helper
 */
#define CONFIG_IP_VS_FTP_MODULE 1
#define CONFIG_NETFILTER 1
#undef CONFIG_NETFILTER_DEBUG
#define CONFIG_BRIDGE_NETFILTER 1

/*
 * IP: Netfilter Configuration
 */
#undef CONFIG_IP_NF_CONNTRACK
#undef CONFIG_IP_NF_CONNTRACK_MARK
#undef CONFIG_IP_NF_QUEUE
#define CONFIG_IP_NF_IPTABLES_MODULE 1
#undef CONFIG_IP_NF_MATCH_LIMIT
#undef CONFIG_IP_NF_MATCH_IPRANGE
#undef CONFIG_IP_NF_MATCH_MAC
#undef CONFIG_IP_NF_MATCH_PKTTYPE
#undef CONFIG_IP_NF_MATCH_MARK
#undef CONFIG_IP_NF_MATCH_MULTIPORT
#undef CONFIG_IP_NF_MATCH_TOS
#undef CONFIG_IP_NF_MATCH_RECENT
#define CONFIG_IP_NF_MATCH_ECN_MODULE 1
#undef CONFIG_IP_NF_MATCH_DSCP
#undef CONFIG_IP_NF_MATCH_AH_ESP
#undef CONFIG_IP_NF_MATCH_LENGTH
#define CONFIG_IP_NF_MATCH_TTL_MODULE 1
#undef CONFIG_IP_NF_MATCH_TCPMSS
#undef CONFIG_IP_NF_MATCH_OWNER
#undef CONFIG_IP_NF_MATCH_PHYSDEV
#undef CONFIG_IP_NF_MATCH_ADDRTYPE
#undef CONFIG_IP_NF_MATCH_REALM
#undef CONFIG_IP_NF_MATCH_SCTP
#undef CONFIG_IP_NF_MATCH_COMMENT
#undef CONFIG_IP_NF_MATCH_HASHLIMIT
#define CONFIG_IP_NF_FILTER_MODULE 1
#define CONFIG_IP_NF_TARGET_REJECT_MODULE 1
#undef CONFIG_IP_NF_TARGET_LOG
#undef CONFIG_IP_NF_TARGET_ULOG
#undef CONFIG_IP_NF_TARGET_TCPMSS
#define CONFIG_IP_NF_MANGLE_MODULE 1
#undef CONFIG_IP_NF_TARGET_TOS
#define CONFIG_IP_NF_TARGET_ECN_MODULE 1
#undef CONFIG_IP_NF_TARGET_DSCP
#undef CONFIG_IP_NF_TARGET_MARK
#undef CONFIG_IP_NF_TARGET_CLASSIFY
#define CONFIG_IP_NF_RAW_MODULE 1
#define CONFIG_IP_NF_ARPTABLES_MODULE 1
#define CONFIG_IP_NF_ARPFILTER_MODULE 1
#define CONFIG_IP_NF_ARP_MANGLE_MODULE 1

/*
 * Bridge: Netfilter Configuration
 */
#define CONFIG_BRIDGE_NF_EBTABLES_MODULE 1
#define CONFIG_BRIDGE_EBT_BROUTE_MODULE 1
#define CONFIG_BRIDGE_EBT_T_FILTER_MODULE 1
#define CONFIG_BRIDGE_EBT_T_NAT_MODULE 1
#define CONFIG_BRIDGE_EBT_802_3_MODULE 1
#define CONFIG_BRIDGE_EBT_AMONG_MODULE 1
#define CONFIG_BRIDGE_EBT_ARP_MODULE 1
#define CONFIG_BRIDGE_EBT_IP_MODULE 1
#define CONFIG_BRIDGE_EBT_LIMIT_MODULE 1
#define CONFIG_BRIDGE_EBT_MARK_MODULE 1
#define CONFIG_BRIDGE_EBT_PKTTYPE_MODULE 1
#define CONFIG_BRIDGE_EBT_STP_MODULE 1
#define CONFIG_BRIDGE_EBT_VLAN_MODULE 1
#define CONFIG_BRIDGE_EBT_ARPREPLY_MODULE 1
#define CONFIG_BRIDGE_EBT_DNAT_MODULE 1
#define CONFIG_BRIDGE_EBT_MARK_T_MODULE 1
#define CONFIG_BRIDGE_EBT_REDIRECT_MODULE 1
#define CONFIG_BRIDGE_EBT_SNAT_MODULE 1
#define CONFIG_BRIDGE_EBT_LOG_MODULE 1
#undef CONFIG_BRIDGE_EBT_ULOG
#define CONFIG_XFRM 1
#define CONFIG_XFRM_USER_MODULE 1
#define CONFIG_BRIDGE_MODULE 1
#define CONFIG_VLAN_8021Q_MODULE 1
#define CONFIG_DECNET_MODULE 1
#define CONFIG_LLC_MODULE 1
#define CONFIG_LLC2_MODULE 1
#define CONFIG_IPX_MODULE 1
#undef CONFIG_IPX_INTERN
#define CONFIG_ATALK_MODULE 1
#undef CONFIG_DEV_APPLETALK

/*
 * QoS and/or fair queueing
 */
#define CONFIG_NET_SCHED 1
#define CONFIG_NET_SCH_CLK_JIFFIES 1
#undef CONFIG_NET_SCH_CLK_GETTIMEOFDAY
#undef CONFIG_NET_SCH_CLK_CPU
#define CONFIG_NET_SCH_CBQ_MODULE 1
#define CONFIG_NET_SCH_HTB_MODULE 1
#define CONFIG_NET_SCH_HFSC_MODULE 1
#define CONFIG_NET_SCH_PRIO_MODULE 1
#define CONFIG_NET_SCH_RED_MODULE 1
#define CONFIG_NET_SCH_SFQ_MODULE 1
#define CONFIG_NET_SCH_TEQL_MODULE 1
#define CONFIG_NET_SCH_TBF_MODULE 1
#define CONFIG_NET_SCH_GRED_MODULE 1
#define CONFIG_NET_SCH_DSMARK_MODULE 1
#define CONFIG_NET_SCH_NETEM_MODULE 1
#define CONFIG_NET_SCH_INGRESS_MODULE 1
#undef CONFIG_NET_QOS
#define CONFIG_NET_CLS 1
#define CONFIG_NET_CLS_TCINDEX_MODULE 1
#define CONFIG_NET_CLS_ROUTE4_MODULE 1
#define CONFIG_NET_CLS_ROUTE 1
#define CONFIG_NET_CLS_FW_MODULE 1
#define CONFIG_NET_CLS_U32_MODULE 1
#undef CONFIG_CLS_U32_PERF
#undef CONFIG_NET_CLS_IND
#define CONFIG_CLS_U32_MARK 1

/*
 * Network testing
 */
#define CONFIG_NET_PKTGEN_MODULE 1
#undef CONFIG_NETPOLL
#undef CONFIG_NET_POLL_CONTROLLER
#define CONFIG_HAMRADIO 1

/*
 * Packet Radio protocols
 */
#define CONFIG_AX25_MODULE 1
#define CONFIG_AX25_DAMA_SLAVE 1
#define CONFIG_NETROM_MODULE 1
#define CONFIG_ROSE_MODULE 1

/*
 * AX.25 network device drivers
 */
#define CONFIG_BPQETHER_MODULE 1
#define CONFIG_SCC_MODULE 1
#undef CONFIG_SCC_DELAY
#undef CONFIG_SCC_TRXECHO
#define CONFIG_BAYCOM_SER_FDX_MODULE 1
#define CONFIG_BAYCOM_SER_HDX_MODULE 1
#define CONFIG_BAYCOM_PAR_MODULE 1
#define CONFIG_BAYCOM_EPP_MODULE 1
#define CONFIG_YAM_MODULE 1
#define CONFIG_IRDA_MODULE 1

/*
 * IrDA protocols
 */
#define CONFIG_IRLAN_MODULE 1
#define CONFIG_IRNET_MODULE 1
#define CONFIG_IRCOMM_MODULE 1
#define CONFIG_IRDA_ULTRA 1

/*
 * IrDA options
 */
#define CONFIG_IRDA_CACHE_LAST_LSAP 1
#define CONFIG_IRDA_FAST_RR 1
#undef CONFIG_IRDA_DEBUG

/*
 * Infrared-port device drivers
 */

/*
 * SIR device drivers
 */
#define CONFIG_IRTTY_SIR_MODULE 1

/*
 * Dongle support
 */
#define CONFIG_DONGLE 1
#define CONFIG_ESI_DONGLE_MODULE 1
#define CONFIG_ACTISYS_DONGLE_MODULE 1
#define CONFIG_TEKRAM_DONGLE_MODULE 1
#define CONFIG_LITELINK_DONGLE_MODULE 1

/*
 * Old SIR device drivers
 */

/*
 * Old Serial dongle support
 */

/*
 * FIR device drivers
 */
#define CONFIG_USB_IRDA_MODULE 1
#define CONFIG_NSC_FIR_MODULE 1
#define CONFIG_WINBOND_FIR_MODULE 1
#define CONFIG_TOSHIBA_FIR_MODULE 1
#define CONFIG_VIA_FIR_MODULE 1
#define CONFIG_BT_MODULE 1
#undef CONFIG_BT_L2CAP
#undef CONFIG_BT_SCO

/*
 * Bluetooth device drivers
 */
#undef CONFIG_BT_HCIUSB
#define CONFIG_BT_HCIUART_MODULE 1
#define CONFIG_BT_HCIUART_H4 1
#define CONFIG_BT_HCIUART_BCSP 1
#undef CONFIG_BT_HCIUART_BCSP_TXCRC
#define CONFIG_BT_HCIBCM203X_MODULE 1
#define CONFIG_BT_HCIBPA10X_MODULE 1
#define CONFIG_BT_HCIBFUSB_MODULE 1
#define CONFIG_BT_HCIDTL1_MODULE 1
#define CONFIG_BT_HCIBT3C_MODULE 1
#define CONFIG_BT_HCIBLUECARD_MODULE 1
#define CONFIG_BT_HCIBTUART_MODULE 1
#define CONFIG_BT_HCIVHCI_MODULE 1
#define CONFIG_NETDEVICES 1
#define CONFIG_DUMMY_MODULE 1
#define CONFIG_BONDING_MODULE 1
#define CONFIG_EQUALIZER_MODULE 1
#define CONFIG_TUN 1
#define CONFIG_NET_SB1000_MODULE 1

/*
 * ARCnet devices
 */
#define CONFIG_ARCNET_MODULE 1
#define CONFIG_ARCNET_1201_MODULE 1
#define CONFIG_ARCNET_1051_MODULE 1
#define CONFIG_ARCNET_RAW_MODULE 1
#define CONFIG_ARCNET_CAP_MODULE 1
#define CONFIG_ARCNET_COM90xx_MODULE 1
#define CONFIG_ARCNET_COM90xxIO_MODULE 1
#define CONFIG_ARCNET_RIM_I_MODULE 1
#define CONFIG_ARCNET_COM20020_MODULE 1
#define CONFIG_ARCNET_COM20020_ISA_MODULE 1
#define CONFIG_ARCNET_COM20020_PCI_MODULE 1

/*
 * Ethernet (10 or 100Mbit)
 */
#undef CONFIG_NET_ETHERNET
#define CONFIG_MII_MODULE 1

/*
 * Ethernet (1000 Mbit)
 */
#define CONFIG_ACENIC_MODULE 1
#undef CONFIG_ACENIC_OMIT_TIGON_I
#define CONFIG_DL2K_MODULE 1
#define CONFIG_E1000_MODULE 1
#undef CONFIG_E1000_NAPI
#define CONFIG_NS83820_MODULE 1
#define CONFIG_HAMACHI_MODULE 1
#define CONFIG_R8169_MODULE 1
#undef CONFIG_R8169_VLAN
#undef CONFIG_SK98LIN
#define CONFIG_TIGON3_MODULE 1

/*
 * Ethernet (10000 Mbit)
 */
#define CONFIG_IXGB_MODULE 1
#define CONFIG_S2IO_MODULE 1
#undef CONFIG_2BUFF_MODE

/*
 * Token Ring devices
 */
#undef CONFIG_TR

/*
 * Wireless LAN (non-hamradio)
 */
#undef CONFIG_NET_RADIO

/*
 * PCMCIA network device support
 */
#undef CONFIG_NET_PCMCIA

/*
 * Wan interfaces
 */
#define CONFIG_WAN 1
#define CONFIG_HOSTESS_SV11_MODULE 1
#define CONFIG_COSA_MODULE 1
#define CONFIG_DSCC4_MODULE 1
#define CONFIG_DSCC4_PCISYNC 1
#define CONFIG_DSCC4_PCI_RST 1
#define CONFIG_LANMEDIA_MODULE 1
#define CONFIG_SEALEVEL_4021_MODULE 1
#undef CONFIG_SYNCLINK_SYNCPPP
#define CONFIG_HDLC_MODULE 1
#undef CONFIG_HDLC_RAW
#undef CONFIG_HDLC_RAW_ETH
#undef CONFIG_HDLC_CISCO
#undef CONFIG_HDLC_FR
#undef CONFIG_HDLC_PPP

/*
 * X.25/LAPB support is disabled
 */
#define CONFIG_PCI200SYN_MODULE 1
#define CONFIG_WANXL_MODULE 1
#undef CONFIG_PC300
#define CONFIG_N2_MODULE 1
#define CONFIG_C101_MODULE 1
#define CONFIG_FARSYNC_MODULE 1
#define CONFIG_DLCI_MODULE 1
#define CONFIG_DLCI_COUNT 24
#define CONFIG_DLCI_MAX 8
#define CONFIG_SDLA_MODULE 1
#define CONFIG_SBNI_MODULE 1
#undef CONFIG_SBNI_MULTILINE
#define CONFIG_FDDI 1
#define CONFIG_DEFXX_MODULE 1
#define CONFIG_SKFP_MODULE 1
#define CONFIG_PLIP_MODULE 1
#define CONFIG_PPP 1
#define CONFIG_PPP_FILTER 1
#define CONFIG_PPP_ASYNC_MODULE 1
#define CONFIG_PPP_SYNC_TTY_MODULE 1
#define CONFIG_PPP_DEFLATE_MODULE 1
#define CONFIG_PPP_BSDCOMP_MODULE 1
#define CONFIG_SLIP_MODULE 1
#define CONFIG_SLIP_COMPRESSED 1
#define CONFIG_SLIP_SMART 1
#define CONFIG_SLIP_MODE_SLIP6 1
#define CONFIG_NET_FC 1

/*
 * ISDN subsystem
 */
#define CONFIG_ISDN 1

/*
 * Old ISDN4Linux
 */
#define CONFIG_ISDN_I4L_MODULE 1
#define CONFIG_ISDN_PPP 1
#define CONFIG_ISDN_PPP_VJ 1
#define CONFIG_ISDN_MPP 1
#define CONFIG_IPPP_FILTER 1
#define CONFIG_ISDN_PPP_BSDCOMP_MODULE 1
#define CONFIG_ISDN_AUDIO 1
#define CONFIG_ISDN_TTY_FAX 1

/*
 * ISDN feature submodules
 */
#define CONFIG_ISDN_DIVERSION_MODULE 1

/*
 * ISDN4Linux hardware drivers
 */

/*
 * Passive cards
 */
#define CONFIG_ISDN_DRV_HISAX_MODULE 1

/*
 * D-channel protocol features
 */
#define CONFIG_HISAX_EURO 1
#define CONFIG_DE_AOC 1
#undef CONFIG_HISAX_NO_SENDCOMPLETE
#undef CONFIG_HISAX_NO_LLC
#undef CONFIG_HISAX_NO_KEYPAD
#define CONFIG_HISAX_1TR6 1
#define CONFIG_HISAX_NI1 1
#define CONFIG_HISAX_MAX_CARDS 8

/*
 * HiSax supported cards
 */
#define CONFIG_HISAX_16_0 1
#define CONFIG_HISAX_16_3 1
#define CONFIG_HISAX_TELESPCI 1
#define CONFIG_HISAX_S0BOX 1
#define CONFIG_HISAX_AVM_A1 1
#define CONFIG_HISAX_FRITZPCI 1
#define CONFIG_HISAX_AVM_A1_PCMCIA 1
#define CONFIG_HISAX_ELSA 1
#define CONFIG_HISAX_IX1MICROR2 1
#define CONFIG_HISAX_DIEHLDIVA 1
#define CONFIG_HISAX_ASUSCOM 1
#define CONFIG_HISAX_TELEINT 1
#define CONFIG_HISAX_HFCS 1
#define CONFIG_HISAX_SEDLBAUER 1
#define CONFIG_HISAX_SPORTSTER 1
#define CONFIG_HISAX_MIC 1
#define CONFIG_HISAX_NETJET 1
#define CONFIG_HISAX_NETJET_U 1
#define CONFIG_HISAX_NICCY 1
#define CONFIG_HISAX_ISURF 1
#define CONFIG_HISAX_HSTSAPHIR 1
#define CONFIG_HISAX_BKM_A4T 1
#define CONFIG_HISAX_SCT_QUADRO 1
#define CONFIG_HISAX_GAZEL 1
#define CONFIG_HISAX_HFC_PCI 1
#define CONFIG_HISAX_W6692 1
#define CONFIG_HISAX_HFC_SX 1
#define CONFIG_HISAX_ENTERNOW_PCI 1
#undef CONFIG_HISAX_DEBUG

/*
 * HiSax PCMCIA card service modules
 */
#define CONFIG_HISAX_SEDLBAUER_CS_MODULE 1
#define CONFIG_HISAX_ELSA_CS_MODULE 1
#define CONFIG_HISAX_AVM_A1_CS_MODULE 1
#define CONFIG_HISAX_TELES_CS_MODULE 1

/*
 * HiSax sub driver modules
 */

/*
 * Active cards
 */
#undef CONFIG_ISDN_DRV_ICN
#undef CONFIG_ISDN_DRV_PCBIT
#undef CONFIG_ISDN_DRV_SC
#undef CONFIG_ISDN_DRV_ACT2000

/*
 * CAPI subsystem
 */
#define CONFIG_ISDN_CAPI_MODULE 1
#undef CONFIG_ISDN_DRV_AVMB1_VERBOSE_REASON
#define CONFIG_ISDN_CAPI_CAPI20_MODULE 1
#define CONFIG_ISDN_CAPI_CAPIDRV_MODULE 1

/*
 * CAPI hardware drivers
 */

/*
 * Active AVM cards
 */
#define CONFIG_CAPI_AVM 1
#define CONFIG_ISDN_DRV_AVMB1_B1ISA_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_B1PCI_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_B1PCIV4 1
#define CONFIG_ISDN_DRV_AVMB1_T1ISA_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_B1PCMCIA_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_AVM_CS_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_T1PCI_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_C4_MODULE 1

/*
 * Active Eicon DIVA Server cards
 */
#define CONFIG_CAPI_EICON 1
#define CONFIG_ISDN_DIVAS_MODULE 1
#define CONFIG_ISDN_DIVAS_BRIPCI 1
#define CONFIG_ISDN_DIVAS_PRIPCI 1
#define CONFIG_ISDN_DIVAS_DIVACAPI_MODULE 1
#define CONFIG_ISDN_DIVAS_USERIDI_MODULE 1
#define CONFIG_ISDN_DIVAS_MAINT_MODULE 1

/*
 * Telephony Support
 */
#undef CONFIG_PHONE

/*
 * Input device support
 */
#define CONFIG_INPUT 1

/*
 * Userland interfaces
 */
#define CONFIG_INPUT_MOUSEDEV 1
#define CONFIG_INPUT_MOUSEDEV_PSAUX 1
#define CONFIG_INPUT_MOUSEDEV_SCREEN_X 1024
#define CONFIG_INPUT_MOUSEDEV_SCREEN_Y 768
#define CONFIG_INPUT_JOYDEV_MODULE 1
#undef CONFIG_INPUT_TSDEV
#define CONFIG_INPUT_EVDEV 1
#define CONFIG_INPUT_EVBUG_MODULE 1

/*
 * Input I/O drivers
 */
#define CONFIG_GAMEPORT_MODULE 1
#define CONFIG_SOUND_GAMEPORT_MODULE 1
#define CONFIG_GAMEPORT_NS558_MODULE 1
#define CONFIG_GAMEPORT_L4_MODULE 1
#define CONFIG_GAMEPORT_EMU10K1_MODULE 1
#undef CONFIG_GAMEPORT_VORTEX
#define CONFIG_GAMEPORT_FM801_MODULE 1
#undef CONFIG_GAMEPORT_CS461X
#define CONFIG_SERIO 1
#define CONFIG_SERIO_I8042 1
#define CONFIG_SERIO_SERPORT_MODULE 1
#define CONFIG_SERIO_CT82C710_MODULE 1
#define CONFIG_SERIO_PARKBD_MODULE 1
#define CONFIG_SERIO_PCIPS2_MODULE 1
#define CONFIG_SERIO_LIBPS2 1
#define CONFIG_SERIO_RAW_MODULE 1

/*
 * Input Device Drivers
 */
#define CONFIG_INPUT_KEYBOARD 1
#define CONFIG_KEYBOARD_ATKBD 1
#define CONFIG_KEYBOARD_SUNKBD_MODULE 1
#define CONFIG_KEYBOARD_LKKBD_MODULE 1
#define CONFIG_KEYBOARD_XTKBD_MODULE 1
#define CONFIG_KEYBOARD_NEWTON_MODULE 1
#define CONFIG_INPUT_MOUSE 1
#define CONFIG_MOUSE_PS2_MODULE 1
#define CONFIG_MOUSE_SERIAL_MODULE 1
#undef CONFIG_MOUSE_INPORT
#define CONFIG_MOUSE_LOGIBM_MODULE 1
#define CONFIG_MOUSE_PC110PAD_MODULE 1
#define CONFIG_MOUSE_VSXXXAA_MODULE 1
#define CONFIG_INPUT_JOYSTICK 1
#define CONFIG_JOYSTICK_ANALOG_MODULE 1
#define CONFIG_JOYSTICK_A3D_MODULE 1
#define CONFIG_JOYSTICK_ADI_MODULE 1
#define CONFIG_JOYSTICK_COBRA_MODULE 1
#define CONFIG_JOYSTICK_GF2K_MODULE 1
#define CONFIG_JOYSTICK_GRIP_MODULE 1
#define CONFIG_JOYSTICK_GRIP_MP_MODULE 1
#define CONFIG_JOYSTICK_GUILLEMOT_MODULE 1
#define CONFIG_JOYSTICK_INTERACT_MODULE 1
#define CONFIG_JOYSTICK_SIDEWINDER_MODULE 1
#define CONFIG_JOYSTICK_TMDC_MODULE 1
#define CONFIG_JOYSTICK_IFORCE_MODULE 1
#define CONFIG_JOYSTICK_IFORCE_USB 1
#define CONFIG_JOYSTICK_IFORCE_232 1
#define CONFIG_JOYSTICK_WARRIOR_MODULE 1
#define CONFIG_JOYSTICK_MAGELLAN_MODULE 1
#define CONFIG_JOYSTICK_SPACEORB_MODULE 1
#define CONFIG_JOYSTICK_SPACEBALL_MODULE 1
#define CONFIG_JOYSTICK_STINGER_MODULE 1
#undef CONFIG_JOYSTICK_TWIDDLER
#define CONFIG_JOYSTICK_DB9_MODULE 1
#define CONFIG_JOYSTICK_GAMECON_MODULE 1
#define CONFIG_JOYSTICK_TURBOGRAFX_MODULE 1
#define CONFIG_JOYSTICK_JOYDUMP_MODULE 1
#define CONFIG_INPUT_TOUCHSCREEN 1
#define CONFIG_TOUCHSCREEN_GUNZE_MODULE 1
#define CONFIG_INPUT_MISC 1
#define CONFIG_INPUT_PCSPKR_MODULE 1
#define CONFIG_INPUT_UINPUT 1

/*
 * Character devices
 */
#define CONFIG_VT 1
#define CONFIG_VT_CONSOLE 1
#define CONFIG_HW_CONSOLE 1
#define CONFIG_SERIAL_NONSTANDARD 1
#define CONFIG_ROCKETPORT_MODULE 1
#define CONFIG_CYCLADES_MODULE 1
#define CONFIG_MOXA_SMARTIO_MODULE 1
#define CONFIG_ISI_MODULE 1
#define CONFIG_SYNCLINK_MODULE 1
#define CONFIG_SYNCLINKMP_MODULE 1
#define CONFIG_N_HDLC_MODULE 1
#undef CONFIG_STALDRV

/*
 * Serial drivers
 */
#define CONFIG_SERIAL_8250 1
#define CONFIG_SERIAL_8250_CONSOLE 1
#define CONFIG_SERIAL_8250_CS_MODULE 1
#undef CONFIG_SERIAL_8250_ACPI
#define CONFIG_SERIAL_8250_NR_UARTS 48
#define CONFIG_SERIAL_8250_EXTENDED 1
#define CONFIG_SERIAL_8250_MANY_PORTS 1
#define CONFIG_SERIAL_8250_SHARE_IRQ 1
#undef CONFIG_SERIAL_8250_DETECT_IRQ
#undef CONFIG_SERIAL_8250_MULTIPORT
#define CONFIG_SERIAL_8250_RSA 1

/*
 * Non-8250 serial port support
 */
#define CONFIG_SERIAL_CORE 1
#define CONFIG_SERIAL_CORE_CONSOLE 1
#define CONFIG_UNIX98_PTYS 1
#define CONFIG_LEGACY_PTYS 1
#define CONFIG_LEGACY_PTY_COUNT 256
#define CONFIG_PRINTER_MODULE 1
#undef CONFIG_LP_CONSOLE
#define CONFIG_PPDEV_MODULE 1
#undef CONFIG_TIPAR

/*
 * IPMI
 */
#define CONFIG_IPMI_HANDLER_MODULE 1
#undef CONFIG_IPMI_PANIC_EVENT
#define CONFIG_IPMI_DEVICE_INTERFACE_MODULE 1
#define CONFIG_IPMI_SI_MODULE 1
#define CONFIG_IPMI_WATCHDOG_MODULE 1
#define CONFIG_IPMI_POWEROFF_MODULE 1

/*
 * Watchdog Cards
 */
#define CONFIG_WATCHDOG 1
#undef CONFIG_WATCHDOG_NOWAYOUT

/*
 * Watchdog Device Drivers
 */
#define CONFIG_SOFT_WATCHDOG_MODULE 1
#define CONFIG_ACQUIRE_WDT_MODULE 1
#define CONFIG_ADVANTECH_WDT_MODULE 1
#define CONFIG_ALIM1535_WDT_MODULE 1
#define CONFIG_ALIM7101_WDT_MODULE 1
#undef CONFIG_SC520_WDT
#define CONFIG_EUROTECH_WDT_MODULE 1
#define CONFIG_IB700_WDT_MODULE 1
#define CONFIG_WAFER_WDT_MODULE 1
#undef CONFIG_I8XX_TCO
#define CONFIG_SC1200_WDT_MODULE 1
#define CONFIG_SCx200_WDT_MODULE 1
#define CONFIG_60XX_WDT_MODULE 1
#define CONFIG_CPU5_WDT_MODULE 1
#define CONFIG_W83627HF_WDT_MODULE 1
#define CONFIG_W83877F_WDT_MODULE 1
#define CONFIG_MACHZ_WDT_MODULE 1

/*
 * ISA-based Watchdog Cards
 */
#define CONFIG_PCWATCHDOG_MODULE 1
#define CONFIG_MIXCOMWD_MODULE 1
#define CONFIG_WDT_MODULE 1
#undef CONFIG_WDT_501

/*
 * PCI-based Watchdog Cards
 */
#define CONFIG_PCIPCWATCHDOG_MODULE 1
#define CONFIG_WDTPCI_MODULE 1
#undef CONFIG_WDT_501_PCI

/*
 * USB-based Watchdog Cards
 */
#define CONFIG_USBPCWATCHDOG_MODULE 1
#define CONFIG_HW_RANDOM 1
#define CONFIG_NVRAM_MODULE 1
#undef CONFIG_RTC
#undef CONFIG_GEN_RTC
#define CONFIG_DTLK_MODULE 1
#undef CONFIG_R3964
#define CONFIG_APPLICOM_MODULE 1

/*
 * Ftape, the floppy tape device driver
 */
#define CONFIG_AGP 1
#define CONFIG_AGP_ALI_MODULE 1
#define CONFIG_AGP_ATI_MODULE 1
#define CONFIG_AGP_AMD 1
#define CONFIG_AGP_AMD64 1
#define CONFIG_AGP_INTEL 1
#undef CONFIG_AGP_INTEL_MCH
#define CONFIG_AGP_NVIDIA 1
#define CONFIG_AGP_SIS_MODULE 1
#define CONFIG_AGP_SWORKS_MODULE 1
#define CONFIG_AGP_VIA 1
#define CONFIG_AGP_EFFICEON_MODULE 1
#define CONFIG_DRM_MODULE 1
#undef CONFIG_DRM_TDFX
#undef CONFIG_DRM_R128
#define CONFIG_DRM_RADEON_MODULE 1
#undef CONFIG_DRM_I810
#undef CONFIG_DRM_I830
#undef CONFIG_DRM_I915
#undef CONFIG_DRM_MGA
#undef CONFIG_DRM_SIS

/*
 * PCMCIA character devices
 */
#define CONFIG_SYNCLINK_CS_MODULE 1
#define CONFIG_MWAVE_MODULE 1
#define CONFIG_SCx200_GPIO_MODULE 1
#define CONFIG_RAW_DRIVER_MODULE 1
#define CONFIG_HPET 1
#undef CONFIG_HPET_RTC_IRQ
#define CONFIG_HPET_MMAP 1
#define CONFIG_MAX_RAW_DEVS 256
#define CONFIG_HANGCHECK_TIMER_MODULE 1

/*
 * I2C support
 */
#define CONFIG_I2C 1
#define CONFIG_I2C_CHARDEV 1

/*
 * I2C Algorithms
 */
#define CONFIG_I2C_ALGOBIT_MODULE 1
#undef CONFIG_I2C_ALGOPCF
#define CONFIG_I2C_ALGOPCA_MODULE 1

/*
 * I2C Hardware Bus support
 */
#define CONFIG_I2C_PARPORT_MODULE 1
#define CONFIG_I2C_PARPORT_LIGHT_MODULE 1
#undef CONFIG_SCx200_I2C
#define CONFIG_SCx200_ACB_MODULE 1
#define CONFIG_I2C_PCA_ISA_MODULE 1

/*
 * Hardware Sensors Chip support
 */
#define CONFIG_I2C_SENSOR_MODULE 1
#define CONFIG_SENSORS_LM83_MODULE 1
#define CONFIG_SENSORS_LM90_MODULE 1

/*
 * Other I2C Chip support
 */
#undef CONFIG_I2C_DEBUG_CORE
#undef CONFIG_I2C_DEBUG_ALGO
#undef CONFIG_I2C_DEBUG_BUS
#undef CONFIG_I2C_DEBUG_CHIP

/*
 * Dallas's 1-wire bus
 */
#define CONFIG_W1_MODULE 1
#undef CONFIG_W1_MATROX
#undef CONFIG_W1_DS9490
#undef CONFIG_W1_THERM
#undef CONFIG_W1_SMEM

/*
 * Misc devices
 */

/*
 * Multimedia devices
 */
#define CONFIG_VIDEO_DEV_MODULE 1

/*
 * Video For Linux
 */

/*
 * Video Adapters
 */
#define CONFIG_VIDEO_BT848_MODULE 1
#undef CONFIG_VIDEO_PMS
#undef CONFIG_VIDEO_BWQCAM
#undef CONFIG_VIDEO_W9966
#undef CONFIG_VIDEO_CPIA
#undef CONFIG_VIDEO_SAA5246A
#undef CONFIG_VIDEO_SAA5249
#undef CONFIG_TUNER_3036
#define CONFIG_VIDEO_ZORAN_MODULE 1
#define CONFIG_VIDEO_ZORAN_BUZ_MODULE 1
#define CONFIG_VIDEO_ZORAN_DC10_MODULE 1
#define CONFIG_VIDEO_ZORAN_DC30_MODULE 1
#define CONFIG_VIDEO_ZORAN_LML33_MODULE 1
#define CONFIG_VIDEO_ZORAN_LML33R10_MODULE 1
#define CONFIG_VIDEO_SAA7134_MODULE 1
#define CONFIG_VIDEO_MXB_MODULE 1
#undef CONFIG_VIDEO_DPC
#define CONFIG_VIDEO_HEXIUM_ORION_MODULE 1
#define CONFIG_VIDEO_HEXIUM_GEMINI_MODULE 1
#undef CONFIG_VIDEO_OVCAMCHIP

/*
 * Radio Adapters
 */
#define CONFIG_RADIO_CADET_MODULE 1
#define CONFIG_RADIO_RTRACK_MODULE 1
#define CONFIG_RADIO_RTRACK2_MODULE 1
#define CONFIG_RADIO_AZTECH_MODULE 1
#define CONFIG_RADIO_GEMTEK_MODULE 1
#undef CONFIG_RADIO_GEMTEK_PCI
#define CONFIG_RADIO_MAXIRADIO_MODULE 1
#undef CONFIG_RADIO_MAESTRO
#define CONFIG_RADIO_SF16FMI_MODULE 1
#define CONFIG_RADIO_SF16FMR2_MODULE 1
#define CONFIG_RADIO_TERRATEC_MODULE 1
#define CONFIG_RADIO_TRUST_MODULE 1
#define CONFIG_RADIO_TYPHOON_MODULE 1
#undef CONFIG_RADIO_TYPHOON_PROC_FS
#define CONFIG_RADIO_ZOLTRIX_MODULE 1

/*
 * Digital Video Broadcasting Devices
 */
#undef CONFIG_DVB
#define CONFIG_VIDEO_SAA7146_MODULE 1
#define CONFIG_VIDEO_SAA7146_VV_MODULE 1
#define CONFIG_VIDEO_VIDEOBUF_MODULE 1
#define CONFIG_VIDEO_TUNER_MODULE 1
#define CONFIG_VIDEO_BUF_MODULE 1
#define CONFIG_VIDEO_BTCX_MODULE 1
#define CONFIG_VIDEO_IR_MODULE 1
#define CONFIG_VIDEO_TVEEPROM_MODULE 1

/*
 * Graphics support
 */
#define CONFIG_FB 1
#define CONFIG_FB_MODE_HELPERS 1
#define CONFIG_FB_TILEBLITTING 1
#define CONFIG_FB_CIRRUS_MODULE 1
#define CONFIG_FB_PM2_MODULE 1
#define CONFIG_FB_PM2_FIFO_DISCONNECT 1
#define CONFIG_FB_CYBER2000_MODULE 1
#define CONFIG_FB_ASILIANT 1
#define CONFIG_FB_IMSTT 1
#define CONFIG_FB_VGA16_MODULE 1
#define CONFIG_FB_VESA 1
#define CONFIG_VIDEO_SELECT 1
#define CONFIG_FB_HGA_MODULE 1
#define CONFIG_FB_RIVA_MODULE 1
#define CONFIG_FB_RIVA_I2C 1
#undef CONFIG_FB_RIVA_DEBUG
#define CONFIG_FB_MATROX_MODULE 1
#define CONFIG_FB_MATROX_MILLENIUM 1
#define CONFIG_FB_MATROX_MYSTIQUE 1
#define CONFIG_FB_MATROX_G 1
#define CONFIG_FB_MATROX_I2C_MODULE 1
#define CONFIG_FB_MATROX_MAVEN_MODULE 1
#undef CONFIG_FB_MATROX_MULTIHEAD
#undef CONFIG_FB_RADEON_OLD
#define CONFIG_FB_RADEON_MODULE 1
#define CONFIG_FB_RADEON_I2C 1
#undef CONFIG_FB_RADEON_DEBUG
#define CONFIG_FB_ATY128_MODULE 1
#define CONFIG_FB_ATY_MODULE 1
#define CONFIG_FB_ATY_CT 1
#undef CONFIG_FB_ATY_GENERIC_LCD
#undef CONFIG_FB_ATY_XL_INIT
#define CONFIG_FB_ATY_GX 1
#define CONFIG_FB_SIS_MODULE 1
#define CONFIG_FB_SIS_300 1
#define CONFIG_FB_SIS_315 1
#define CONFIG_FB_NEOMAGIC_MODULE 1
#define CONFIG_FB_KYRO_MODULE 1
#define CONFIG_FB_3DFX_MODULE 1
#define CONFIG_FB_VOODOO1_MODULE 1
#define CONFIG_FB_TRIDENT_MODULE 1
#undef CONFIG_FB_VIRTUAL

/*
 * Console display driver support
 */
#define CONFIG_VGA_CONSOLE 1
#define CONFIG_MDA_CONSOLE_MODULE 1
#define CONFIG_DUMMY_CONSOLE 1
#define CONFIG_FRAMEBUFFER_CONSOLE 1
#define CONFIG_FONTS 1
#define CONFIG_FONT_8x8 1
#define CONFIG_FONT_8x16 1
#undef CONFIG_FONT_6x11
#undef CONFIG_FONT_PEARL_8x8
#define CONFIG_FONT_ACORN_8x8 1
#undef CONFIG_FONT_MINI_4x6
#undef CONFIG_FONT_SUN8x16
#undef CONFIG_FONT_SUN12x22

/*
 * Logo configuration
 */
#undef CONFIG_LOGO
#define CONFIG_BACKLIGHT_LCD_SUPPORT 1
#define CONFIG_BACKLIGHT_CLASS_DEVICE 1
#define CONFIG_BACKLIGHT_DEVICE 1
#define CONFIG_LCD_CLASS_DEVICE_MODULE 1
#define CONFIG_LCD_DEVICE 1

/*
 * Sound
 */
#define CONFIG_SOUND_MODULE 1

/*
 * Advanced Linux Sound Architecture
 */
#define CONFIG_SND_MODULE 1
#define CONFIG_SND_TIMER_MODULE 1
#define CONFIG_SND_PCM_MODULE 1
#define CONFIG_SND_HWDEP_MODULE 1
#define CONFIG_SND_RAWMIDI_MODULE 1
#define CONFIG_SND_SEQUENCER_MODULE 1
#define CONFIG_SND_SEQ_DUMMY_MODULE 1
#define CONFIG_SND_OSSEMUL 1
#define CONFIG_SND_MIXER_OSS_MODULE 1
#undef CONFIG_SND_PCM_OSS
#undef CONFIG_SND_SEQUENCER_OSS
#undef CONFIG_SND_VERBOSE_PRINTK
#undef CONFIG_SND_DEBUG

/*
 * Generic devices
 */
#define CONFIG_SND_MPU401_UART_MODULE 1
#define CONFIG_SND_OPL3_LIB_MODULE 1
#define CONFIG_SND_OPL4_LIB_MODULE 1
#define CONFIG_SND_VX_LIB_MODULE 1
#define CONFIG_SND_DUMMY_MODULE 1
#define CONFIG_SND_VIRMIDI_MODULE 1
#define CONFIG_SND_MTPAV_MODULE 1
#define CONFIG_SND_SERIAL_U16550_MODULE 1
#define CONFIG_SND_MPU401_MODULE 1

/*
 * ISA devices
 */
#define CONFIG_SND_AD1816A_MODULE 1
#define CONFIG_SND_AD1848_MODULE 1
#define CONFIG_SND_CS4231_MODULE 1
#undef CONFIG_SND_CS4232
#define CONFIG_SND_CS4236_MODULE 1
#undef CONFIG_SND_ES968
#define CONFIG_SND_ES1688_MODULE 1
#define CONFIG_SND_ES18XX_MODULE 1
#define CONFIG_SND_GUS_SYNTH_MODULE 1
#define CONFIG_SND_GUSCLASSIC_MODULE 1
#define CONFIG_SND_GUSEXTREME_MODULE 1
#define CONFIG_SND_GUSMAX_MODULE 1
#define CONFIG_SND_INTERWAVE_MODULE 1
#define CONFIG_SND_INTERWAVE_STB_MODULE 1
#define CONFIG_SND_OPTI92X_AD1848_MODULE 1
#define CONFIG_SND_OPTI92X_CS4231_MODULE 1
#define CONFIG_SND_OPTI93X_MODULE 1
#define CONFIG_SND_SB8_MODULE 1
#define CONFIG_SND_SB16_MODULE 1
#define CONFIG_SND_SBAWE_MODULE 1
#define CONFIG_SND_SB16_CSP 1
#define CONFIG_SND_WAVEFRONT_MODULE 1
#define CONFIG_SND_ALS100_MODULE 1
#define CONFIG_SND_AZT2320_MODULE 1
#define CONFIG_SND_CMI8330_MODULE 1
#undef CONFIG_SND_DT019X
#define CONFIG_SND_OPL3SA2_MODULE 1
#undef CONFIG_SND_SGALAXY
#define CONFIG_SND_SSCAPE_MODULE 1

/*
 * PCI devices
 */
#define CONFIG_SND_AC97_CODEC_MODULE 1
#define CONFIG_SND_ALI5451_MODULE 1
#define CONFIG_SND_ATIIXP_MODULE 1
#define CONFIG_SND_ATIIXP_MODEM_MODULE 1
#define CONFIG_SND_AU8810_MODULE 1
#define CONFIG_SND_AU8820_MODULE 1
#define CONFIG_SND_AU8830_MODULE 1
#define CONFIG_SND_BT87X_MODULE 1
#undef CONFIG_SND_BT87X_OVERCLOCK
#define CONFIG_SND_CS46XX_MODULE 1
#define CONFIG_SND_CS4281_MODULE 1
#define CONFIG_SND_EMU10K1_MODULE 1
#define CONFIG_SND_EMU10K1X_MODULE 1
#define CONFIG_SND_CA0106_MODULE 1
#define CONFIG_SND_KORG1212_MODULE 1
#define CONFIG_SND_MIXART_MODULE 1
#define CONFIG_SND_NM256_MODULE 1
#define CONFIG_SND_RME32_MODULE 1
#define CONFIG_SND_RME96_MODULE 1
#define CONFIG_SND_RME9652_MODULE 1
#define CONFIG_SND_HDSP_MODULE 1
#define CONFIG_SND_TRIDENT_MODULE 1
#define CONFIG_SND_YMFPCI_MODULE 1
#define CONFIG_SND_ALS4000_MODULE 1
#define CONFIG_SND_CMIPCI_MODULE 1
#define CONFIG_SND_ENS1370_MODULE 1
#define CONFIG_SND_ENS1371_MODULE 1
#define CONFIG_SND_ES1938_MODULE 1
#define CONFIG_SND_ES1968_MODULE 1
#define CONFIG_SND_MAESTRO3_MODULE 1
#define CONFIG_SND_FM801_MODULE 1
#undef CONFIG_SND_FM801_TEA575X
#define CONFIG_SND_ICE1712_MODULE 1
#define CONFIG_SND_ICE1724_MODULE 1
#define CONFIG_SND_INTEL8X0_MODULE 1
#define CONFIG_SND_SONICVIBES_MODULE 1
#define CONFIG_SND_VIA82XX_MODULE 1
#define CONFIG_SND_VIA82XX_MODEM_MODULE 1
#define CONFIG_SND_VX222_MODULE 1

/*
 * USB devices
 */
#define CONFIG_SND_USB_AUDIO_MODULE 1
#define CONFIG_SND_USB_USX2Y_MODULE 1

/*
 * PCMCIA devices
 */
#define CONFIG_SND_VXPOCKET_MODULE 1
#undef CONFIG_SND_VXP440
#define CONFIG_SND_PDAUDIOCF_MODULE 1

/*
 * Open Sound System
 */
#undef CONFIG_SOUND_PRIME

/*
 * USB support
 */
#define CONFIG_USB 1
#undef CONFIG_USB_DEBUG

/*
 * Miscellaneous USB options
 */
#undef CONFIG_USB_DEVICEFS
#define CONFIG_USB_ARCH_HAS_HCD 1
#define CONFIG_USB_ARCH_HAS_OHCI 1

/*
 * USB Host Controller Drivers
 */
#define CONFIG_USB_EHCI_HCD 1
#define CONFIG_USB_OHCI_HCD 1
#define CONFIG_USB_UHCI_HCD 1
#define CONFIG_USB_SL811_HCD_MODULE 1

/*
 * USB Device Class drivers
 */
#define CONFIG_USB_AUDIO_MODULE 1

/*
 * USB Bluetooth TTY can only be used with disabled Bluetooth subsystem
 */
#undef CONFIG_USB_MIDI
#define CONFIG_USB_ACM_MODULE 1
#define CONFIG_USB_PRINTER_MODULE 1

/*
 * NOTE: USB_STORAGE enables SCSI, and 'SCSI disk support' may also be needed; see USB_STORAGE Help for more information
 */
#define CONFIG_USB_STORAGE_MODULE 1
#undef CONFIG_USB_STORAGE_DEBUG
#undef CONFIG_USB_STORAGE_FREECOM
#undef CONFIG_USB_STORAGE_DPCM

/*
 * USB Input Devices
 */
#define CONFIG_USB_HID_MODULE 1
#define CONFIG_USB_HIDINPUT 1
#define CONFIG_USB_HIDDEV 1

/*
 * USB HID Boot Protocol drivers
 */
#define CONFIG_USB_KBD_MODULE 1
#define CONFIG_USB_MOUSE_MODULE 1
#undef CONFIG_USB_AIPTEK
#undef CONFIG_USB_WACOM
#undef CONFIG_USB_KBTAB
#undef CONFIG_USB_POWERMATE
#undef CONFIG_USB_MTOUCH
#undef CONFIG_USB_EGALAX
#undef CONFIG_USB_XPAD
#undef CONFIG_USB_ATI_REMOTE

/*
 * USB Imaging devices
 */
#define CONFIG_USB_MICROTEK_MODULE 1

/*
 * USB Multimedia devices
 */
#undef CONFIG_USB_DABUSB
#undef CONFIG_USB_IBMCAM
#undef CONFIG_USB_KONICAWC
#undef CONFIG_USB_OV511
#undef CONFIG_USB_SE401
#undef CONFIG_USB_SN9C102
#undef CONFIG_USB_STV680

/*
 * USB Network Adapters
 */
#define CONFIG_USB_KAWETH_MODULE 1
#define CONFIG_USB_PEGASUS_MODULE 1
#define CONFIG_USB_USBNET_MODULE 1

/*
 * USB Host-to-Host Cables
 */
#define CONFIG_USB_ALI_M5632 1
#define CONFIG_USB_AN2720 1
#define CONFIG_USB_BELKIN 1
#define CONFIG_USB_GENESYS 1
#define CONFIG_USB_NET1080 1

/*
 * Intelligent USB Devices/Gadgets
 */
#define CONFIG_USB_ARMLINUX 1
#define CONFIG_USB_EPSON2888 1
#define CONFIG_USB_ZAURUS 1
#define CONFIG_USB_CDCETHER 1

/*
 * USB Network Adapters
 */

/*
 * USB port drivers
 */
#define CONFIG_USB_USS720_MODULE 1

/*
 * USB Serial Converter support
 */
#define CONFIG_USB_SERIAL_MODULE 1
#define CONFIG_USB_SERIAL_GENERIC 1
#define CONFIG_USB_SERIAL_BELKIN_MODULE 1
#define CONFIG_USB_SERIAL_DIGI_ACCELEPORT_MODULE 1
#define CONFIG_USB_SERIAL_EMPEG_MODULE 1
#define CONFIG_USB_SERIAL_VISOR_MODULE 1
#define CONFIG_USB_SERIAL_IPAQ_MODULE 1
#define CONFIG_USB_SERIAL_EDGEPORT_MODULE 1
#define CONFIG_USB_SERIAL_EDGEPORT_TI_MODULE 1
#define CONFIG_USB_SERIAL_GARMIN_MODULE 1
#define CONFIG_USB_SERIAL_KEYSPAN_PDA_MODULE 1
#define CONFIG_USB_SERIAL_KEYSPAN_MODULE 1
#define CONFIG_USB_SERIAL_KEYSPAN_MPR 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA28 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA28X 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA28XA 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA28XB 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA19 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA18X 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA19W 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA19QW 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA19QI 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA49W 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA49WLC 1
#define CONFIG_USB_SERIAL_KOBIL_SCT_MODULE 1
#define CONFIG_USB_SERIAL_MCT_U232_MODULE 1
#define CONFIG_USB_SERIAL_PL2303_MODULE 1
#define CONFIG_USB_SERIAL_TI_MODULE 1
#define CONFIG_USB_SERIAL_XIRCOM_MODULE 1
#define CONFIG_USB_EZUSB 1

/*
 * USB Miscellaneous drivers
 */
#define CONFIG_USB_EMI62_MODULE 1
#define CONFIG_USB_EMI26_MODULE 1
#define CONFIG_USB_LCD_MODULE 1
#undef CONFIG_USB_LED
#define CONFIG_USB_CYTHERM_MODULE 1
#undef CONFIG_USB_PHIDGETKIT
#undef CONFIG_USB_PHIDGETSERVO
#define CONFIG_USB_IDMOUSE_MODULE 1

/*
 * USB ATM/DSL drivers
 */

/*
 * USB Gadget Support
 */
#define CONFIG_USB_GADGET_MODULE 1
#undef CONFIG_USB_GADGET_DEBUG_FILES
#define CONFIG_USB_GADGET_NET2280 1
#define CONFIG_USB_NET2280_MODULE 1
#undef CONFIG_USB_GADGET_PXA2XX
#undef CONFIG_USB_GADGET_GOKU
#undef CONFIG_USB_GADGET_SA1100
#undef CONFIG_USB_GADGET_LH7A40X
#undef CONFIG_USB_GADGET_DUMMY_HCD
#undef CONFIG_USB_GADGET_OMAP
#define CONFIG_USB_GADGET_DUALSPEED 1
#undef CONFIG_USB_ZERO
#define CONFIG_USB_ETH_MODULE 1
#undef CONFIG_USB_GADGETFS
#undef CONFIG_USB_FILE_STORAGE
#define CONFIG_USB_G_SERIAL_MODULE 1

/*
 * MMC/SD Card support
 */
#define CONFIG_MMC 1
#undef CONFIG_MMC_DEBUG
#define CONFIG_MMC_BLOCK_MODULE 1
#define CONFIG_MMC_WBSD_MODULE 1

/*
 * InfiniBand support
 */
#define CONFIG_INFINIBAND_MODULE 1
#define CONFIG_INFINIBAND_MTHCA_MODULE 1
#undef CONFIG_INFINIBAND_MTHCA_DEBUG
#define CONFIG_INFINIBAND_IPOIB_MODULE 1
#undef CONFIG_INFINIBAND_IPOIB_DEBUG

/*
 * File systems
 */
#undef CONFIG_EXT2_FS
#undef CONFIG_EXT3_FS
#undef CONFIG_JBD
#define CONFIG_REISERFS_FS_MODULE 1
#undef CONFIG_REISERFS_CHECK
#undef CONFIG_REISERFS_PROC_INFO
#define CONFIG_REISERFS_FS_XATTR 1
#define CONFIG_REISERFS_FS_POSIX_ACL 1
#define CONFIG_REISERFS_FS_SECURITY 1
#define CONFIG_JFS_FS_MODULE 1
#define CONFIG_JFS_POSIX_ACL 1
#define CONFIG_JFS_SECURITY 1
#undef CONFIG_JFS_DEBUG
#define CONFIG_JFS_STATISTICS 1
#define CONFIG_FS_POSIX_ACL 1

/*
 * XFS support
 */
#define CONFIG_XFS_FS_MODULE 1
#define CONFIG_XFS_EXPORT 1
#define CONFIG_XFS_QUOTA 1
#undef CONFIG_XFS_SECURITY
#define CONFIG_XFS_POSIX_ACL 1
#define CONFIG_MINIX_FS_MODULE 1
#define CONFIG_ROMFS_FS_MODULE 1
#define CONFIG_QUOTA 1
#define CONFIG_QFMT_V1_MODULE 1
#define CONFIG_QFMT_V2_MODULE 1
#define CONFIG_QUOTACTL 1
#define CONFIG_DNOTIFY 1
#undef CONFIG_AUTOFS_FS
#define CONFIG_AUTOFS4_FS_MODULE 1

/*
 * CD-ROM/DVD Filesystems
 */
#define CONFIG_ISO9660_FS_MODULE 1
#define CONFIG_JOLIET 1
#define CONFIG_ZISOFS 1
#define CONFIG_ZISOFS_FS_MODULE 1
#define CONFIG_UDF_FS_MODULE 1
#define CONFIG_UDF_NLS 1

/*
 * DOS/FAT/NT Filesystems
 */
#define CONFIG_FAT_FS 1
#define CONFIG_MSDOS_FS_MODULE 1
#define CONFIG_VFAT_FS 1
#define CONFIG_FAT_DEFAULT_CODEPAGE 437
#define CONFIG_FAT_DEFAULT_IOCHARSET "iso8859-1"
#define CONFIG_NTFS_FS_MODULE 1
#undef CONFIG_NTFS_DEBUG
#undef CONFIG_NTFS_RW

/*
 * Pseudo filesystems
 */
#define CONFIG_PROC_FS 1
#define CONFIG_PROC_KCORE 1
#define CONFIG_SYSFS 1
#undef CONFIG_DEVPTS_FS_XATTR
#define CONFIG_TMPFS 1
#define CONFIG_TMPFS_XATTR 1
#undef CONFIG_TMPFS_SECURITY
#define CONFIG_HUGETLBFS 1
#define CONFIG_HUGETLB_PAGE 1
#define CONFIG_RAMFS 1
#define CONFIG_EXT2_FS 1

/*
 * Miscellaneous filesystems
 */
#define CONFIG_HFSPLUS_FS_MODULE 1
#undef CONFIG_JFFS_FS
#define CONFIG_JFFS2_FS_MODULE 1
#define CONFIG_JFFS2_FS_DEBUG 0
#undef CONFIG_JFFS2_FS_NAND
#define CONFIG_JFFS2_COMPRESSION_OPTIONS 1
#define CONFIG_JFFS2_ZLIB 1
#define CONFIG_JFFS2_RTIME 1
#undef CONFIG_JFFS2_RUBIN
#undef CONFIG_JFFS2_CMODE_NONE
#define CONFIG_JFFS2_CMODE_PRIORITY 1
#undef CONFIG_JFFS2_CMODE_SIZE
#define CONFIG_CRAMFS_MODULE 1
#define CONFIG_VXFS_FS_MODULE 1
#define CONFIG_HPFS_FS_MODULE 1
#define CONFIG_QNX4FS_FS_MODULE 1
#define CONFIG_SYSV_FS_MODULE 1
#define CONFIG_UFS_FS_MODULE 1

/*
 * Network File Systems
 */
#define CONFIG_NFS_FS_MODULE 1
#undef CONFIG_NFS_V3
#define CONFIG_NFSD_MODULE 1
#define CONFIG_NFSD_V3 1
#define CONFIG_NFSD_TCP 1
#define CONFIG_LOCKD_MODULE 1
#define CONFIG_LOCKD_V4 1
#define CONFIG_EXPORTFS_MODULE 1
#define CONFIG_SUNRPC_MODULE 1
#undef CONFIG_SMB_FS
#define CONFIG_CIFS_MODULE 1
#define CONFIG_CIFS_STATS 1
#define CONFIG_CIFS_XATTR 1
#define CONFIG_CIFS_POSIX 1
#undef CONFIG_CIFS_EXPERIMENTAL
#define CONFIG_NCP_FS_MODULE 1
#define CONFIG_NCPFS_PACKET_SIGNING 1
#define CONFIG_NCPFS_IOCTL_LOCKING 1
#define CONFIG_NCPFS_STRONG 1
#define CONFIG_NCPFS_NFS_NS 1
#define CONFIG_NCPFS_OS2_NS 1
#undef CONFIG_NCPFS_SMALLDOS
#define CONFIG_NCPFS_NLS 1
#define CONFIG_NCPFS_EXTRAS 1
#define CONFIG_CODA_FS_MODULE 1
#undef CONFIG_CODA_FS_OLD_API

/*
 * Partition Types
 */
#define CONFIG_PARTITION_ADVANCED 1
#undef CONFIG_ACORN_PARTITION
#define CONFIG_OSF_PARTITION 1
#define CONFIG_AMIGA_PARTITION 1
#define CONFIG_ATARI_PARTITION 1
#define CONFIG_MAC_PARTITION 1
#define CONFIG_MSDOS_PARTITION 1
#define CONFIG_BSD_DISKLABEL 1
#define CONFIG_MINIX_SUBPARTITION 1
#define CONFIG_SOLARIS_X86_PARTITION 1
#define CONFIG_UNIXWARE_DISKLABEL 1
#define CONFIG_LDM_PARTITION 1
#undef CONFIG_LDM_DEBUG
#define CONFIG_SGI_PARTITION 1
#define CONFIG_ULTRIX_PARTITION 1
#define CONFIG_SUN_PARTITION 1
#define CONFIG_EFI_PARTITION 1

/*
 * Native Language Support
 */
#define CONFIG_NLS 1
#define CONFIG_NLS_DEFAULT "utf8"
#define CONFIG_NLS_CODEPAGE_437 1
#define CONFIG_NLS_CODEPAGE_737_MODULE 1
#define CONFIG_NLS_CODEPAGE_775_MODULE 1
#define CONFIG_NLS_CODEPAGE_850_MODULE 1
#define CONFIG_NLS_CODEPAGE_852_MODULE 1
#define CONFIG_NLS_CODEPAGE_855_MODULE 1
#define CONFIG_NLS_CODEPAGE_857_MODULE 1
#define CONFIG_NLS_CODEPAGE_860_MODULE 1
#define CONFIG_NLS_CODEPAGE_861_MODULE 1
#define CONFIG_NLS_CODEPAGE_862_MODULE 1
#define CONFIG_NLS_CODEPAGE_863_MODULE 1
#define CONFIG_NLS_CODEPAGE_864_MODULE 1
#define CONFIG_NLS_CODEPAGE_865_MODULE 1
#define CONFIG_NLS_CODEPAGE_866_MODULE 1
#define CONFIG_NLS_CODEPAGE_869_MODULE 1
#define CONFIG_NLS_CODEPAGE_936_MODULE 1
#define CONFIG_NLS_CODEPAGE_950_MODULE 1
#define CONFIG_NLS_CODEPAGE_932_MODULE 1
#define CONFIG_NLS_CODEPAGE_949_MODULE 1
#define CONFIG_NLS_CODEPAGE_874_MODULE 1
#define CONFIG_NLS_ISO8859_8_MODULE 1
#define CONFIG_NLS_CODEPAGE_1250_MODULE 1
#define CONFIG_NLS_CODEPAGE_1251_MODULE 1
#define CONFIG_NLS_ASCII_MODULE 1
#define CONFIG_NLS_ISO8859_1_MODULE 1
#define CONFIG_NLS_ISO8859_2_MODULE 1
#define CONFIG_NLS_ISO8859_3_MODULE 1
#define CONFIG_NLS_ISO8859_4_MODULE 1
#define CONFIG_NLS_ISO8859_5_MODULE 1
#define CONFIG_NLS_ISO8859_6_MODULE 1
#define CONFIG_NLS_ISO8859_7_MODULE 1
#define CONFIG_NLS_ISO8859_9_MODULE 1
#define CONFIG_NLS_ISO8859_13_MODULE 1
#define CONFIG_NLS_ISO8859_14_MODULE 1
#define CONFIG_NLS_ISO8859_15_MODULE 1
#define CONFIG_NLS_KOI8_R_MODULE 1
#define CONFIG_NLS_KOI8_U_MODULE 1
#define CONFIG_NLS_UTF8_MODULE 1

/*
 * Kernel hacking
 */
#define CONFIG_DEBUG_KERNEL 1
#define CONFIG_MAGIC_SYSRQ 1
#define CONFIG_SCHEDSTATS 1
#undef CONFIG_DEBUG_SLAB
#undef CONFIG_DEBUG_SPINLOCK
#undef CONFIG_DEBUG_SPINLOCK_SLEEP
#undef CONFIG_DEBUG_KOBJECT
#undef CONFIG_DEBUG_HIGHMEM
#define CONFIG_DEBUG_BUGVERBOSE 1
#define CONFIG_DEBUG_INFO 1
#define CONFIG_DEBUG_FS 1
#define CONFIG_FRAME_POINTER 1
#define CONFIG_EARLY_PRINTK 1
#undef CONFIG_DEBUG_STACKOVERFLOW
#define CONFIG_KPROBES 1
#undef CONFIG_DEBUG_STACK_USAGE
#undef CONFIG_DEBUG_PAGEALLOC
#undef CONFIG_4KSTACKS
#define CONFIG_X86_FIND_SMP_CONFIG 1
#define CONFIG_X86_MPPARSE 1

/*
 * Security options
 */
#define CONFIG_KEYS 1
#undef CONFIG_KEYS_DEBUG_PROC_KEYS
#define CONFIG_SECURITY 1
#define CONFIG_SECURITY_NETWORK 1
#undef CONFIG_SECURITY_CAPABILITIES
#undef CONFIG_SECURITY_ROOTPLUG
#undef CONFIG_SECURITY_SECLVL
#define CONFIG_SECURITY_SELINUX 1
#define CONFIG_SECURITY_SELINUX_BOOTPARAM 1
#define CONFIG_SECURITY_SELINUX_BOOTPARAM_VALUE 0
#undef CONFIG_SECURITY_SELINUX_DISABLE
#define CONFIG_SECURITY_SELINUX_DEVELOP 1
#define CONFIG_SECURITY_SELINUX_AVC_STATS 1

/*
 * Cryptographic options
 */
#define CONFIG_CRYPTO 1
#define CONFIG_CRYPTO_HMAC 1
#define CONFIG_CRYPTO_NULL 1
#define CONFIG_CRYPTO_MD4_MODULE 1
#define CONFIG_CRYPTO_MD5 1
#define CONFIG_CRYPTO_SHA1 1
#define CONFIG_CRYPTO_SHA256 1
#define CONFIG_CRYPTO_SHA512 1
#define CONFIG_CRYPTO_WP512_MODULE 1
#define CONFIG_CRYPTO_DES_MODULE 1
#define CONFIG_CRYPTO_BLOWFISH_MODULE 1
#define CONFIG_CRYPTO_TWOFISH_MODULE 1
#define CONFIG_CRYPTO_SERPENT_MODULE 1
#define CONFIG_CRYPTO_AES_586_MODULE 1
#define CONFIG_CRYPTO_CAST5_MODULE 1
#define CONFIG_CRYPTO_CAST6_MODULE 1
#define CONFIG_CRYPTO_TEA_MODULE 1
#define CONFIG_CRYPTO_ARC4_MODULE 1
#define CONFIG_CRYPTO_KHAZAD_MODULE 1
#define CONFIG_CRYPTO_ANUBIS_MODULE 1
#define CONFIG_CRYPTO_DEFLATE_MODULE 1
#define CONFIG_CRYPTO_MICHAEL_MIC_MODULE 1
#define CONFIG_CRYPTO_CRC32C 1
#define CONFIG_CRYPTO_TEST_MODULE 1

/*
 * Hardware crypto devices
 */
#define CONFIG_CRYPTO_DEV_PADLOCK 1
#define CONFIG_CRYPTO_DEV_PADLOCK_AES 1

/*
 * Library routines
 */
#define CONFIG_CRC_CCITT 1
#define CONFIG_CRC32 1
#define CONFIG_LIBCRC32C 1
#define CONFIG_ZLIB_INFLATE_MODULE 1
#define CONFIG_ZLIB_DEFLATE_MODULE 1
#define CONFIG_GENERIC_HARDIRQS 1
#define CONFIG_GENERIC_IRQ_PROBE 1
#define CONFIG_X86_SMP 1
#define CONFIG_X86_HT 1
#define CONFIG_X86_BIOS_REBOOT 1
#define CONFIG_X86_TRAMPOLINE 1
#define CONFIG_PC 1
